export class Product {

    constructor(
        id:number,
        brandName:string,
        category:string,
        subcategoryName:string,
        subsubcategoryName:string,
        productName_en:string,
        productName_ar:string,
        product_code:number,
        product_qty:number,
        productTags_en:string[],
        productTags_ar:string[],
        productSize_en:string[],
        productSize_ar:string[],
        productColor_en:string[],
        productColor_ar:string[],
        price:number,
        discountPrice:number,
        shortDescp_en:string,
        shortDescp_ar:string,
        longDescp_en:string,
        longDescp_ar:string,
        productImgPath:string,
        productImges:string[],
        hot_deals:boolean,
        featured:boolean,
        special_offer:boolean,
        special_deals:boolean,
        status: 1,
        adminName:string,
        rate:number
    ){}
}
